const $=s=>document.querySelector(s);
const fmt=(v,u)=>{if(v===null||v===undefined||Number.isNaN(Number(v)))return '—';const n=Number(v);if(u==='$')return '$'+n.toLocaleString(undefined,{maximumFractionDigits:2});if(u==='%')return n.toLocaleString(undefined,{maximumFractionDigits:2})+'%';if(u==='index')return n.toLocaleString(undefined,{maximumFractionDigits:2});if(u==='M')return n.toLocaleString(undefined,{maximumFractionDigits:2})+'M';return n.toLocaleString(undefined,{maximumFractionDigits:2})};
const deltaClass=d=>d>0?'good':d<0?'bad':'flat';
const deltaText=(d,u)=>{if(d===null||d===undefined||Number.isNaN(Number(d)))return '—';const sign=d>0?'+':'';return sign+Number(d).toFixed(2)+(u==='%'?' pp':'')};
function sourceAnchor(x){return x.source_url?'<a class="source-link" href="'+x.source_url+'" target="_blank" rel="noreferrer">'+(x.source||'Source')+'</a>':(x.source||'—')}
function makeTable(items){let rows='';items.forEach(x=>{rows+='<tr><td><strong>'+x.name+'</strong></td><td>'+fmt(x.value,x.unit)+'</td><td class="'+deltaClass(x.change)+'">'+deltaText(x.change,x.unit)+'</td><td>'+(x.date||'—')+'</td><td>'+(x.frequency||'—')+'</td><td>'+sourceAnchor(x)+'</td></tr>'});return '<div class="table-wrap"><table><thead><tr><th>Indicator</th><th>Latest</th><th>Change</th><th>Obs. date</th><th>Frequency</th><th>Source</th></tr></thead><tbody>'+rows+'</tbody></table></div>'}
function makeSpark(canvas,series){if(!window.Chart||!series||series.length<2)return;new Chart(canvas,{type:'line',data:{labels:series.map(x=>x.date),datasets:[{data:series.map(x=>x.value),borderWidth:2,pointRadius:0,tension:.28,fill:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}})}
async function load(){
$('#today').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'short',day:'numeric',year:'numeric'}).format(new Date());
try{const r=await fetch('data/indicators.json',{cache:'no-store'});if(!r.ok)throw new Error('Data file unavailable');const d=await r.json();$('#lastUpdated').textContent='Data refreshed: '+new Date(d.generated_at).toLocaleString();
const pulse=d.sections.pulse||[];let cards='';pulse.forEach((x,i)=>{cards+='<article class="metric-card"><div class="metric-name">'+x.name+'</div><div class="metric-value">'+fmt(x.value,x.unit)+'</div><div class="delta '+deltaClass(x.change)+'">'+deltaText(x.change,x.unit)+'</div><canvas class="spark" id="sp'+i+'"></canvas><div class="meta"><span>'+(x.date||'')+'</span><span>'+(x.frequency||'')+'</span></div></article>'});$('#pulseGrid').innerHTML=cards;pulse.forEach((x,i)=>makeSpark(document.getElementById('sp'+i),x.history));
$('#usTable').innerHTML=makeTable(d.sections.us||[]);$('#texasTable').innerHTML=makeTable(d.sections.texas||[]);$('#saudiTable').innerHTML=makeTable(d.sections.saudi||[]);$('#globalTable').innerHTML=makeTable(d.sections.global||[]);
}catch(e){$('#pulseGrid').innerHTML='<div class="error">The dashboard could not load its data yet. The first refresh may still be running.</div>'}}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active-panel'));b.classList.add('active');document.getElementById(b.dataset.target).classList.add('active-panel')}));
window.addEventListener('DOMContentLoaded',load);